//------------------------------------------------------------------------------
// <autogenerated>
//     This Oxygene source code was generated by a tool.
//     Runtime Version: 4.0.30319.42000
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

{$HIDE H7}
{$HIDE W1}
{$HIDE W27}
{$HIDE H11}

namespace ng2AspNet;

interface

type
    _Default = public partial class
    protected 
        var tbsFontAwesome: System.Web.UI.HtmlControls.HtmlLink;
        var head: System.Web.UI.WebControls.ContentPlaceHolder;
        var ContentPlaceHolder1: System.Web.UI.WebControls.ContentPlaceHolder;
    end;
    
implementation

end.
